<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-21T01:34:11 IST" name="Suite" finished-at="2025-10-21T01:34:21 IST" duration-ms="9676">
    <groups>
    </groups>
    <test started-at="2025-10-21T01:34:11 IST" name="LoginTest" finished-at="2025-10-21T01:34:17 IST" duration-ms="6227">
      <class name="com.CRM.TestCase.LoginPageTestCase">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.CRM.TestCase.LoginPageTestCase@22a637e7]" started-at="2025-10-21T01:34:11 IST" name="setUp" finished-at="2025-10-21T01:34:16 IST" duration-ms="4796" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="pageSetup()[pri:0, instance:com.CRM.TestCase.LoginPageTestCase@22a637e7]" started-at="2025-10-21T01:34:16 IST" name="pageSetup" finished-at="2025-10-21T01:34:17 IST" duration-ms="800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageSetup -->
        <test-method signature="validateLogin()[pri:0, instance:com.CRM.TestCase.LoginPageTestCase@22a637e7]" started-at="2025-10-21T01:34:17 IST" name="validateLogin" finished-at="2025-10-21T01:34:17 IST" duration-ms="613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
      </class> <!-- com.CRM.TestCase.LoginPageTestCase -->
    </test> <!-- LoginTest -->
    <test started-at="2025-10-21T01:34:17 IST" name="HomePageTest" finished-at="2025-10-21T01:34:21 IST" duration-ms="3427">
      <class name="com.CRM.TestCase.HomePageTestCase">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.CRM.TestCase.HomePageTestCase@1817d444]" started-at="2025-10-21T01:34:17 IST" name="setUp" finished-at="2025-10-21T01:34:20 IST" duration-ms="2208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyUrl()[pri:1, instance:com.CRM.TestCase.HomePageTestCase@1817d444]" started-at="2025-10-21T01:34:20 IST" name="verifyUrl" finished-at="2025-10-21T01:34:20 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUrl -->
        <test-method signature="verifyTitle()[pri:2, instance:com.CRM.TestCase.HomePageTestCase@1817d444]" started-at="2025-10-21T01:34:20 IST" name="verifyTitle" finished-at="2025-10-21T01:34:20 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Fail: Title is not matched! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Fail: Title is not matched! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at com.CRM.TestCase.HomePageTestCase.verifyTitle(HomePageTestCase.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method signature="validateSignInLink()[pri:3, instance:com.CRM.TestCase.HomePageTestCase@1817d444]" started-at="2025-10-21T01:34:20 IST" name="validateSignInLink" finished-at="2025-10-21T01:34:21 IST" duration-ms="1196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSignInLink -->
      </class> <!-- com.CRM.TestCase.HomePageTestCase -->
    </test> <!-- HomePageTest -->
  </suite> <!-- Suite -->
</testng-results>
